---
title: "Analyse de survie"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```

<div class="important">
Ce chapitre est en cours d'écriture.
</div>

L'extension centrale pour l'analyse de survie est `survival`{.pkg}.

Un très bon tutoriel (en anglais et en 3 étapes), introduisant les concepts de l'analyse de survie, des courbes de Kaplan-Meier et des modèles de Cox et leur mise en oeuvre pratique sous **R** est disponible en ligne :

- <http://www.sthda.com/english/wiki/survival-analysis-basics>
- <http://www.sthda.com/english/wiki/cox-proportional-hazards-model>
- <http://www.sthda.com/english/wiki/cox-model-assumptions>

Pour un autre exemple (toujours en anglais) d'analyse de survie avec `survival`{.pkg}, on pourra se référer à <https://rpubs.com/vinubalan/hrsurvival>.

Pour représenter vos résultats avec `ggplot2`{.pkg}, on pourra avoir recours à l'extension `survminer`{.pkg} présentée en détails sur son site officiel (en anglais) : <http://www.sthda.com/english/rpkgs/survminer/>. On pourra également avoir recours à la fonction `ggsurv`{data-pkg="GGally"} de l'extension `GGally`{.pkg} présentée à l'adresse <http://ggobi.github.io/ggally/#ggallyggsurv>.

A noter, il est possible d'utiliser la fonction `step`{data-pkg="stats"} sur un modèle de Cox, pour une sélection pas à pas d'un meilleur modèle basé sur une minimisation de l'AIC (voir le chapitre sur la [régression logistique](regression-logistique.html)). 

L'excellente extension `broom`{.pkg} peut également être utilisée sur des modèles de survie (Kaplan-Meier ou Cox) pour en convertir les résultats sous la forme d'un tableau de données.

Pour approfondir les possibilités offertes par l'extension `survival`{.pkg}, on pourra également consulter les différentes vignettes fournies avec l'extension (voir <https://cran.r-project.org/package=survival>).


