---
title: "Analyse spatiale"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```

Il est tout à fait possible de réaliser des analyses spatiales sous **R**. Historiquement, l'extension principale pour la gestion des objets spatiaux sous **R** est l'extension `sp`{.pkg}. Depuis quelques années, une nouvelle extension `sf`{.pkg} s'est développée. Alors, faut-il plutôt apprendre `sp`{.pkg} ou `sf`{.pkg} ? Chris Brown tente de répondre à cette question dans son billet [Should I learn sf or sp for spatial R programming?](http://www.seascapemodels.org/rstats/2018/03/23/should-I-learn-sp-or-sf.html). Ces deux extensions ont leurs avantages et inconvénients. Du fait que `sp`{.pkg} est plus ancienne, elle est compatible avec plus d'autres extensions. De l'autre côté, `sf`{.pkg} peut s'avérer plus simple pour le néophyte. Dans tous les cas, l'extension `raster`{.pkg} sera un bon complément pour gérer les données de type <dfn>raster</dfn>.

Pour une présentation détaillée (en anglais) de l'analyse spatiale sous **R**, on pourra se référer à l'ouvrage *Geocomputation with R* de Robin Lovelace, Jakub Nowosad et Jannes Muenchow, consultable en ligne (<https://geocompr.robinlovelace.net/>). Cette ouvrage privilégie plutôt l'extension `sf`{.pkg}.

On pourra également se référer aux différentes vignettes inclues par leurs extensions et consultables en ligne sur :

- <https://cran.r-project.org/package=sp> pour `sp`{.pkg}
- <https://cran.r-project.org/package=sf> pour `sf`{.pkg}
- <https://cran.r-project.org/package=raster> pour `raster`{.pkg}

Pour la réalisation de cartes avec **R**, on pourra se référer au [chapitre dédié](cartes.html).

Enfin, le site [Awesome R](https://awesome-r.com/#awesome-r-spatial) fournit une sélection d'extensions dédiées à l'analyse spatiale.
