---
title: "Cartes"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```

<div class="notes">
Pour une présentation de l'analyse spatiale sous **R**, se référer au [chapitre dédié](analyse-spatiale.html).
</div>

Il existe de multiple approches pour réaliser des cartes sous **R**, y compris avec `ggplot2`{.pkg}, mais également de manière native avec les extensions `sp`{.pkg} et `sf`{.pkg}. Il existe également des extensions apportant des fonctionalités additionnelles comme `ggmap`{.pkg}, `mapview`{.pkg} ou encore `tmap`{.pkg}.

Pour une introduction succincte en français, on pourra se référer à la section 5.4 du spport de cours [Logiciel R et programmation](http://egallic.fr/Enseignement/R/m1_stat_eco_logiciel_R.pdf) d'Ewan Gallic.

Timothée Giraud & Hugues Pecout propose un support d'apprentissage *Cartographie avec R* pour créer des cartes thématiques conformes aux règles de la sémiologie graphique et de la cartographie avec R : <https://rcarto.github.io/cartographie_avec_r/>.

Un deuxième manuel centré sur la cartographie est disponible : *Géomatique avec R*, <https://rcarto.github.io/geomatique_avec_r/>.

Voir également l'excellente présentation *Données géospatiales et cartographie avec R* de Nicolas Roelandt : <https://roelandtn.frama.io/slides/2090628_meetup_Raddict_datageo.html>.

En complément (en anglais), la vignette [Plotting Simple Features](https://cran.r-project.org/web/packages/sf/vignettes/sf5.html) de l'extension `sf`{.pkg} ou encore le chapitre [Making maps with R](https://geocompr.robinlovelace.net/adv-map.html) de l'ouvrage *Geocomputation with R* de Robin Lovelace, Jakub Nowosad et Jannes Muenchow.

On pourra également se référer à l'excellent package `mapsf`{.pkg} et à son site dédié <https://riatelab.github.io/mapsf/>. `mapsf`{.pkg} succède à `cartography`{.pkg} (<https://github.com/riatelab/cartography/>) dont une présentation en vidéo et en français est disponible sur <https://youtu.be/OI3_AOg6pfc>.

