---
title: "Export de données"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```

<dfn data-index="données, exporter"></dfn><dfn data-index="exporter des données"></dfn>

<div class="important">
Ce chapitre est en cours d'écriture.
</div>

**R** propose différentes fonctions permettant d'exporter des données vers des formats variés.

| Type de fichier souhaité | Fonction | Extension |
|:---|:---|:---|
| texte | `write.table`{data-pkg="utils"} | `utils`{.pkg} |
| CSV | `write.csv`{data-pkg="utils" data-rdoc="write.table"} | `utils`{.pkg} |
| CSV | `write_csv`{data-pkg="readr"} | `readr`{.pkg} |
| Excel | `write.xlsx`{data-pkg="xlsx"} | `xlsx`{.pkg} |
| dBase | `write.dbf`{data-pkg="foreign"} | `foreign`{.pkg} |
| SPSS | `write_sav`{data-pkg="haven"} | `haven`{.pkg} |
| SPSS | `write.foreign`{data-pkg="foreign"} | `foreign`{.pkg} |
| Stata | `write.dta`{data-pkg="foreign"} | `foreign`{.pkg} |
| Stata | `write_dta`{data-pkg="haven"} | `haven`{.pkg} |
| SAS | `write.foreign`{data-pkg="foreign"} | `foreign`{.pkg} |
| SPSS | `write.foreign`{data-pkg="foreign"} | `foreign`{.pkg} |
| Shapefile | `writePointsShape`{data-pkg="maptools" data-rdoc="readShapePoints"} | `maptools`{.pkg} |
| Shapefile | `writeLinesShape`{data-pkg="maptools" data-rdoc="readShapeLines"} | `maptools`{.pkg} |
| Shapefile | `writePolyShape`{data-pkg="maptools" data-rdoc="readShapePoly"} | `maptools`{.pkg} |
| ASCII Grid | `writeAsciiGrid`{data-pkg="maptools" data-rdoc="readAsciiGrid"} | `maptools`{.pkg} |

À nouveau, pour plus de détails on se référera aux pages d'aide de ces fonctions et au manuel 
<cite>R Data Import/Export</cite> accessible à l'adresse suivante : <http://cran.r-project.org/manuals.html>.
