---
title: "Installation de R et RStudio"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```

Il est préférable de commencer par installer **R** avant d'installer **RStudio**.

## Installation de R

Pour une <dfn>installation</dfn> sous **Windows**, on se rendra sur cette page :
<http://cran.r-project.org/bin/windows/base/> et l'on suivra le premier lien
pour télécharger le programme d'installation. Une fois le programme d'installation
lancé, il suffira d'installer **R** avec les options par défaut^[Dans le cas particulier
où votre ordinateur est situé derrière un <dfn>proxy</dfn>, 
il est préférable de choisir
*Options de démarrage personnalisées* lorsque cela vous sera demandé par le programme
d'installation, puis *Internet2* lorsqu'on vous demandera le mode de connexion
à Internet. Ainsi, **R** utilisera par défaut la configuration internet du navigateur
**Internet Explorer** et prendra ainsi en compte les paramètres du *proxy*.].

Pour **Mac OS X**, les fichiers d'installation sont disponibles à 
<http://cran.r-project.org/bin/macosx/>.

Si vous travaillez sous **Linux**, vous devriez pouvoir trouver **R** via votre
gestionnaire de paquets, cela pouvant dépendre d'une distribution de **Linux**
à une autre.

## Installation de RStudio

Une fois **R** correctement installé, rendez-vous sur
<http://www.rstudio.com/products/rstudio/download/> pour télécharger la dernière
version stable de **RStudio**. Plus précisément, il s'agit de l'édition *Open Source*
de **RStudio Desktop** (en effet, il existe aussi une version serveur).

Choisissez l'installateur correspondant à votre système d'exploitation et suivez
les instructions du programme d'installation.

Si vous voulez tester les dernières fonctionnalités de **RStudio**, vous pouvez
télécharger la version de développement (plus riche en fonctionnalités que la
version stable, mais pouvant contenir des bugs) sur
<http://www.rstudio.com/products/rstudio/download/preview/>.

## Mise à jour de R sous Windows

Pour mettre à jour **R** sous **Windows**<dfn data-index="mise à jour, R"></dfn>, 
il suffit de télécharger et d'installer la dernière version du programme d'installation.

Petite particularité, la nouvelle version sera installée à côté de l'ancienne version.
Si vous souhaitez faire de la place sur votre disque dur, vous pouvez désinstaller l'ancienne
version en utilisant l'utilitaire *Désinstaller un programme* de **Windows**.

Lorsque plusieurs versions de **R** sont disponibles, **RStudio** choisit par défaut la plus récente.
Il est vous est possible de spécifier à **RStudio** quelle version de **R** utiliser via le menu
*Tools* > *Global Options* > *General*.

Petit défaut, les extensions (*packages*) sont installées par défaut sous **Windows** dans le
répertoire `Documents de l'utilisateur > R > win-library > x.y` avec `x.y` correspondant
au numéro de la version de **R**. Ainsi, si l'on travaillait avec la version 3.0 et que l'on passe
à la version 3.2, les extensions que l'on avait sous l'ancienne version ne sont plus disponibles
pour la nouvelle version. Une astuce consiste à recopier le contenu du répertoire `3.0` dans le répertoire
`3.2`. Puis, on lancera **RStudio** (s'il était déjà ouvert, on le fermera puis relancera) et on mettra à
jour l'ensemble des packages, soit avec la fonction, `update.packages`{data-pkg="utils"} soit en cliquant
sur *Update* dans l'onglet *Packages* du quadrant inférieur droit.

