---
title: "Quel type de modèles choisir ?"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```


## Tableau synthétique


<div style="font-size:.85em;" class="code_no_background table_compact">

| Variable à expliquer | Type de modèle | Interprétation des coefficients | Modèle de base | Échantillonnage complexe | Modèle mixte | GEE* |
|:------|:------|:------|:------|:------|:------|:------|
| **Continue** | Linéaire | directe | <code>`stats`{.pkg}::`lm`{data-pkg="stats"}()</code> | &nbsp; | <code>`lme4`{.pkg}::`lmer`{data-pkg="lme4"}()</code> | &nbsp; |
| &nbsp; | Gaussien | directe | <code>`stats`{.pkg}::`glm`{data-pkg="stats"} (family = `gaussian`{data-pkg="stats"})</code> | <code>`survey`{.pkg}::`svyglm`{data-pkg="survey"}<br />(family = `gaussian`{data-pkg="stats"})</code> | <code>`lme4`{.pkg}::`glmer`{data-pkg="lme4"} (family = `gaussian`{data-pkg="stats"})</code> | <code>`geepack`{.pkg}::`geeglm`{data-pkg="geepack"} (family = `gaussian`{data-pkg="stats"})</code> |
| **Comptage**<br />(nombre d'occurences) | Poisson | RR<br />(risques relatifs) | <code>`stats`{.pkg}::`glm`{data-pkg="stats"} (family = `poisson`{data-pkg="stats"})</code> | <code>`survey`{.pkg}::`svyglm`{data-pkg="survey"}<br />(family = `quasipoisson`{data-pkg="stats"})</code> | <code>`lme4`{.pkg}::`glmer`{data-pkg="lme4"} (family = `poisson`{data-pkg="stats"})</code> | <code>`geepack`{.pkg}::`geeglm`{data-pkg="geepack"} (family = `poisson`{data-pkg="stats"})</code> |
| &nbsp; | Binomial négatif | RR<br />(risques relatifs) | <code>`MASS`{.pkg}::`glm.nb`{data-pkg="MASS"}()</code> | <code>`sjstats`{.pkg}::`svyglm.nb`{data-pkg="sjstats"}()</code><br /><br /><code>`svrepmisc`{.pkg}::`svynb`{data-pkg="svrepmisc"}()</code> | <code>`lme4`{.pkg}::`glmer.nb`{data-pkg="lme4"}()</code> | &nbsp; |
| **Ratio / Incidence** | Poisson avec `offset`{data-pkg="stats"} | IRR<br />(*incidence rate ratio*) | <code>`stats`{.pkg}::`glm`{data-pkg="stats"} (family = `poisson`{data-pkg="stats"})</code> | <code>`survey`{.pkg}::`svyglm`{data-pkg="survey"}<br />(family = `quasipoisson`{data-pkg="stats"})</code> | <code>`lme4`{.pkg}::`glmer`{data-pkg="lme4"} (family = `poisson`{data-pkg="stats"})</code> | <code>`geepack`{.pkg}::`geeglm`{data-pkg="geepack"} (family = `poisson`{data-pkg="stats"})</code> |
| &nbsp; | Binomial négatif avec `offset`{data-pkg="stats"} | IRR<br />(*incidence rate ratio*) | <code>`MASS`{.pkg}::`glm.nb`{data-pkg="MASS"}()</code> | <code>`sjstats`{.pkg}::`svyglm.nb`{data-pkg="sjstats"}()</code><br /><br /><code>`svrepmisc`{.pkg}::`svynb`{data-pkg="svrepmisc"}()</code> | <code>`lme4`{.pkg}::`glmer.nb`{data-pkg="lme4"}()</code> | &nbsp; |
| **Binaire**<br />(oui / non) | Logistique (logit) | OR<br />(odds ratio) | <code>`stats`{.pkg}::`glm`{data-pkg="stats"} (family = `binomial`{data-pkg="stats"}(`"logit"`))</code> | <code>`survey`{.pkg}::`svyglm`{data-pkg="survey"}<br />(family = `quasibinomial`{data-pkg="stats"}(`"logit"`))</code> | <code>`lme4`{.pkg}::`glmer`{data-pkg="lme4"} (family = `binomial`{data-pkg="stats"}(`"logit"`))</code> | <code>`geepack`{.pkg}::`geeglm`{data-pkg="geepack"} (family = `binomial`{data-pkg="stats"}(`"logit"`))</code> |
| &nbsp; | Probit | pas interprétable directement | <code>`stats`{.pkg}::`glm`{data-pkg="stats"} (family = `binomial`{data-pkg="stats"}(`"probit"`))</code> | <code>`survey`{.pkg}::`svyglm`{data-pkg="survey"}<br />(family = `quasibinomial`{data-pkg="stats"}(`"probit"`))</code> | <code>`lme4`{.pkg}::`glmer`{data-pkg="lme4"} (family = `binomial`{data-pkg="stats"}(`"probit"`))</code> | <code>`geepack`{.pkg}::`geeglm`{data-pkg="geepack"} (family = `binomial`{data-pkg="stats"}(`"probit"`))</code> |
| &nbsp; | Log binomial | RR<br />(risques relatifs)<br />PR<br />(*prevalence ratio*) | <code>`stats`{.pkg}::`glm`{data-pkg="stats"} (family = `binomial`{data-pkg="stats"}(`"log"`))</code> | <code>`survey`{.pkg}::`svyglm`{data-pkg="survey"}<br />(family = `quasibinomial`{data-pkg="stats"}(`"log"`))</code> | <code>`lme4`{.pkg}::`glmer`{data-pkg="lme4"} (family = `binomial`{data-pkg="stats"}(`"log"`))</code> | <code>`geepack`{.pkg}::`geeglm`{data-pkg="geepack"} (family = `binomial`{data-pkg="stats"}(`"log"`))</code> |
| **Catégorielle ordinale**<br />(3 modalités ou plus) | Régression logistique ordinale | OR<br />(odds ratio) | <code>`ordinal`{.pkg}::`clm`{data-pkg="ordinal"}()</code><br/><br/><code>`VGAM`{.pkg}::`vglm`{data-pkg="VGAM"} (family = `cumulative`{data-pkg="VGAM"}(`parallel = TRUE`))</code><br/><br/><code>`MASS`{.pkg}::`polr`{data-pkg="MASS"}()</code> | <code>`svrepmisc`{.pkg}::`svyclm`{data-pkg="svrepmisc"}()</code><br/><br/><code>`svyVGAM`{.pkg}::`svy_vglm`{data-pkg="svyVGAM"} (family = `cumulative`{data-pkg="VGAM"}(`parallel = TRUE`))</code><br/><br/><code>`survey`{.pkg}::`svyolr`{data-pkg="survey"}()</code> | <code>`ordinal`{.pkg}::`clmm`{data-pkg="ordinal"}()</code> | <code>`geepack`{.pkg}::`ordgee`{data-pkg="geepack"}()</code><br/><br/><code>`multgee`{.pkg}::`ordLORgee`{data-pkg="multgee"}()</code> |
| **Catégorielle nominale**<br />(3 modalités ou plus) | Régression logistique multinomiale | OR<br />(odds ratio) | <code>`nnet`{.pkg}::`multinom`{data-pkg="nnet"}()</code><br/><br/><code>`VGAM`{.pkg}::`vglm`{data-pkg="VGAM"} (family = `multinomial`{data-pkg="VGAM"})</code> | <code>`svrepmisc`{.pkg}::`svymultinom`{data-pkg="svrepmisc"}()</code><br/><br/><code>`svyVGAM`{.pkg}::`svy_vglm`{data-pkg="svyVGAM"} (family = `multinomial`{data-pkg="VGAM"})</code> | &nbsp; | <code>`multgee`{.pkg}::`nomLORgee`{data-pkg="multgee"}()</code> |
| **Survie**<br />(*time to event*) | Cox | HR<br />(*hazard ratio*) | <code>`survival`{.pkg}::`coxph`{data-pkg="survival"}()</code> | <code>`survey`{.pkg}::`svycoxph`{data-pkg="survey"}()</code> | <code>`survival`{.pkg}::`coxph`{data-pkg="survival"}()</code> avec un terme `frailty`{data-pkg="survival"}<br/><br/><code>`coxme`{.pkg}::`coxme`{data-pkg="coxme"}()</code> | <code>`survival`{.pkg}::`coxph`{data-pkg="survival"}()</code> avec l'option `cluster` |
| &nbsp; | Modèle à temps discret binomial cloglog | HR<br />(*hazard ratio*) | <code>`stats`{.pkg}::`glm`{data-pkg="stats"} (family = `binomial`{data-pkg="stats"}(`"cloglog"`))</code> | <code>`survey`{.pkg}::`svyglm`{data-pkg="survey"}<br />(family = `quasibinomial`{data-pkg="stats"}(`"cloglog"`))</code> | <code>`lme4`{.pkg}::`glmer`{data-pkg="lme4"} (family = `binomial`{data-pkg="stats"}(`"cloglog"`))</code> | <code>`geepack`{.pkg}::`geeglm`{data-pkg="geepack"} (family = `binomial`{data-pkg="stats"}(`"cloglog"`))</code> |
| &nbsp; | Accelerated failure time (AFT) | HR<br />(*hazard ratio*) | <code>`survival`{.pkg}::`survreg`{data-pkg="survival"}()</code> | <code>`survey`{.pkg}::`svysurvreg`{data-pkg="survey"}()</code> | <code>`survival`{.pkg}::`survreg`{data-pkg="survival"}()</code> avec un terme `frailty`{data-pkg="survival"} | <code>`survival`{.pkg}::`survreg`{data-pkg="survival"}()</code> avec l'option `cluster` |
| **Comptage avec surreprésentation de zéros** | Zero-inflated Poisson | OR & RR | <code>`pscl`{.pkg}::`zeroinfl`{data-pkg="pscl"}()</code> | <code>`sjstats`{.pkg}::`svyglm.zip`{data-pkg="sjstats"}()</code> | &nbsp; | &nbsp; |
| &nbsp; | Zero-inflated negtaive binomial | OR & RR | <code>`pscl`{.pkg}::`zeroinfl`{data-pkg="pscl"} (`dist = "negbin"`)</code> | <code>`sjstats`{.pkg}::`svyglm.zip`{data-pkg="sjstats"} (`dist = "negbin"`)</code> | &nbsp; | &nbsp; |

\* Voir aussi <code>`gee`{.pkg}::`gee`{data-pkg="gee"}</code> comme alternative à <code>`geepack`{.pkg}::`geeglm`{data-pkg="geepack"}</code>

</div>

