if (!require(devtools)) install.packages("devtools")
library(devtools)
if (!require(questionr)) install_github("juba/questionr")
if (!require(effects)) install.packages("effects")
if (!require(lubridate)) install_github("hadley/lubridate")
if (!exists("time_length")) install_github("hadley/lubridate")
if (!require(eeptools)) install.packages("eeptools")
if (!require(ade4)) install.packages("ade4")
if (!require(FactoMineR)) install.packages("FactoMineR")
if (!require(JLutils)) install_github("larmarange/JLutils")
if (!require(RColorBrewer)) install.packages("RColorBrewer")
if (!require(flashClust)) install.packages("flashClust")
if (!require(cluster)) install.packages("cluster")
if (!require(stringr)) install.packages("stringr")
if (!require(xml2)) install.packages("xml2")
if (!require(TraMineR)) install.packages("TraMineR")
if (!require(ggplot2)) install.packages("ggplot2")
